name: Build

on:
  push:
    branches:
      - master
      - x11-client-experimental
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt install -y libarchive-tools libwayland-bin
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Restore cache
      uses: actions/cache@v3
      with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

          restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Build companion package
      run: |
        ./build_termux_package
    - name: Copy loader to target directory
      run: |
        cp ./shell-loader/build/outputs/apk/debug/shell-loader-debug.apk ./app/build/outputs/apk/debug/shell-loader-nightly.apk
    - name: Store generated files
      uses: actions/upload-artifact@v3
      with:
        name: termux-x11
        path: ./app/build/outputs/apk/debug
