name: Build

on:
  push:
    branches:
      - master
      - x11-client-experimental
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Build companion package
      run: |
        ./build_termux_package
    - name: Store generated APK file
      uses: actions/upload-artifact@v3
      with:
        name: termux-x11
        path: ./app/build/outputs/apk/debug
