name: Build APK

on:
  push:
    branches:
      - master
      - x11-client-experimental
    paths-ignore:
      - "**.md"
      - "img/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "img/**"

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: bash ./gradlew assembleDebug

      - name: Install libarchive-tools
        run: sudo apt install -y libarchive-tools

      - name: Build companion package
        run: bash ./build_termux_package

      - name: Store generated APK file
        uses: actions/upload-artifact@v3
        with:
          name: termux-x11
          path: ./app/build/outputs/apk/debug
