name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - master
      - x11-client-experimental
    paths-ignore:
      - "**.md"
      - "img/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "img/**"

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: gradle/wrapper-validation-action@v1
