name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Restore cache
      uses: actions/cache@v3
      with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

          restore-keys: |
            ${{ runner.os }}-gradle-
            
    - name: Execute tests
      run: |
        ./gradlew test --stacktrace
    - name: Android Integration Test
      uses: ReactiveCircus/android-emulator-runner@v2.27.0
      with:
          api-level: 28
          script: ./gradlew test
